#!/usr/bin/env bash
# Configure ssh client so that you can connect to a server without typing a passwond

Host *
    SendENV LANG LC_*
    HashKnowHosts yes
    GSSAPIAuthentication yes
    GSSAPIDelegateCredentials no
    IdentifyFile ~/.ssh/school
    PasswordAuthentication no
